#pragma once
enum Mode{
    MODE_ACTIVE,
    MODE_LENGTH,
    MODE_RATE,
    MODE_OFFSET,
    MODE_SAMPLE_START,
    MODE_SAMPLE_END,
    MODE_BANK,
    MODE_GLOBAL,
};

enum Command{
    CMD_SET_MODE,
    CMD_PRESS_STEP,
    CMD_SELECT_STEP,
    CMD_SHIFTA,
    CMD_SHIFTB,
    CMD_SHIFTC,
    CMD_SET_GLOBAL_MODE,
    CMD_RANDOMIZE,
    CMD_STARTSTOP,
};
